/-
Copyright (c) 2026 Florian Lengyel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Florian Lengyel
-/
import FailureOfComposition

/-!
Audit the complete types and hypotheses of the maintained public results.
-/

-- Full theorem types expose mathematical hypotheses independently of axioms.
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_functional
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_composition
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_pair_code_eval
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_prec_zero_eval
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_prec_succ_eval
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_rfind_code_eval
#check @FailureOfComposition.ConcreteEvaluator.stageComputation_iff_evaln
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_adequate
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_normal_form
#check @FailureOfComposition.ConcreteNormalForm.normalFormGraph_realizes
#check @FailureOfComposition.ConcreteNormalForm.computationPredicate_nat
#check @FailureOfComposition.ArithmeticCodeCompiler.computes_compile
#check @FailureOfComposition.ArithmeticCodeCompiler.computes_unaryCompile
#check @FailureOfComposition.ArithmeticCodeCompiler.unaryCompile_realizes
#check @FailureOfComposition.HistoryWitnesses.guardCode_eval
#check @FailureOfComposition.HistoryWitnesses.searchCode_eval
#check @FailureOfComposition.HistoryWitnesses.guard_search_empty
#check @FailureOfComposition.HistoryWitnesses.guard_pointwise_identity
#check @FailureOfComposition.HistoryWitnesses.graph_noncongruence_of_history_divergence
#check @FailureOfComposition.theorem_codes_re_of_delta1
#check @FailureOfComposition.theorem_codes_re_of_axiom_codes
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_via_productiveness
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_of_delta_one
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_of_axiom_enumerator
#check @FailureOfComposition.theorem_codes_re_of_program_enumerator

-- All-model formula compilation and full PA-provable graph realization.
#check @FailureOfComposition.ArithmeticFormulaAtoms.termCode_eval
#check @FailureOfComposition.ArithmeticFormulaAtoms.atomCode_eval
#check @FailureOfComposition.ArithmeticFormulaAtoms.negAtomCode_eval
#check @FailureOfComposition.BoundedSemidecision.computes_boundedAll
#check @FailureOfComposition.SigmaOneRealization.Semidecides
#check @FailureOfComposition.SigmaOneSearch.candidateSearch_domain
#check @FailureOfComposition.SigmaOneSearch.candidateSearch_of_functional
#check @FailureOfComposition.SigmaOneSearch.computes_existsProgram
#check @FailureOfComposition.SigmaOneSearch.computes_unionProgram
#check @FailureOfComposition.SigmaOneRealization.semidecision_exists
#check @FailureOfComposition.SigmaOneRealization.realize_of_semidecides
#check @FailureOfComposition.SigmaOneRealization.realize_graph
#check @FailureOfComposition.ConcreteEvaluator.arithmetization

-- The concrete Godel-II route and its theory-presentation bridge.
#check @FailureOfComposition.ConcreteIndices.index_noncongruence_via_godel
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_via_godel
#check @FailureOfComposition.ConcreteIndices.pa_no_index_quotient_via_godel
#check @FailureOfComposition.ConcreteIndices.index_noncongruence_via_godel_of_equivalent_presentation
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_via_godel_of_equivalent_presentation
#check @FailureOfComposition.CraigPresentation.exists_craig_presentation
#check @FailureOfComposition.ConcreteIndices.index_noncongruence_via_godel_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_via_godel_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_via_godel_of_axiom_enumerator

-- Transport is an equivalence of quotient sets, with representative equations.
#check @FailureOfComposition.ArithmetizationTransport.translate_uniform
#check @FailureOfComposition.ArithmetizationTransport.translate_pointwise_iff
#check @FailureOfComposition.ArithmetizationTransport.translate_roundtrip
#check @FailureOfComposition.ArithmetizationTransport.translate_composition
#check @FailureOfComposition.ArithmetizationTransport.quotientEquiv
#check @FailureOfComposition.ArithmetizationTransport.quotientEquiv_composition
#check @FailureOfComposition.ConcreteTransport.toConcrete_uniform
#check @FailureOfComposition.ConcreteTransport.toConcrete_pointwise_iff
#check @FailureOfComposition.ConcreteTransport.quotientEquiv
#check @FailureOfComposition.ConcreteTransport.toConcrete_composition

-- The abstract versions expose their representation-law parameters.
#check @FailureOfComposition.ProgramIndices.Arithmetization
#check @FailureOfComposition.ProgramIndices.no_index_quotient_via_productiveness
#check @FailureOfComposition.ProgramIndices.no_index_quotient_of_re_axioms

-- Pi-one completeness characterizes graph and program-index composition.
#check @FailureOfComposition.quotient_composition_exists_iff
#check @FailureOfComposition.PiOneCharacterization.PiOneComplete
#check @FailureOfComposition.PiOneCharacterization.pointwise_comp_left
#check @FailureOfComposition.PiOneCharacterization.congruence_iff_rightCompatible
#check @FailureOfComposition.PiOneCharacterization.graph_noncongruence_of_true_unprovable_pi_one
#check @FailureOfComposition.PiOneCharacterization.rightCompatible_implies_piOneComplete
#check @FailureOfComposition.PiOneCharacterization.sigma_one_sound_of_pi_one_complete
#check @FailureOfComposition.PiOneCharacterization.pointwise_iff_extensional
#check @FailureOfComposition.PiOneCharacterization.rightCompatible_iff_piOneComplete
#check @FailureOfComposition.PiOneCharacterization.compositionCongruence_iff_piOneComplete
#check @FailureOfComposition.PiOneCharacterization.agreesWithExtensional_iff_piOneComplete
#check @FailureOfComposition.PiOneCharacterization.characterization
#check @FailureOfComposition.PiOneCharacterization.quotient_composition_exists_iff_congruence
#check @FailureOfComposition.PiOneCharacterization.no_quotient_composition_iff_not_piOneComplete
#check @FailureOfComposition.ProgramIndices.rightCompatible_iff_graph
#check @FailureOfComposition.ProgramIndices.compositionCongruence_iff_graph
#check @FailureOfComposition.ProgramIndices.agreesWithExtensional_iff_graph
#check @FailureOfComposition.ProgramIndices.rightCompatible_iff_piOneComplete
#check @FailureOfComposition.ProgramIndices.compositionCongruence_iff_piOneComplete
#check @FailureOfComposition.ProgramIndices.agreesWithExtensional_iff_piOneComplete
#check @FailureOfComposition.ProgramIndices.pointwiseIndex_iff_evaluation_eq
#check @FailureOfComposition.ProgramIndices.characterization
#check @FailureOfComposition.ProgramIndices.quotient_composition_exists_iff_congruence
#check @FailureOfComposition.ProgramIndices.no_index_quotient_iff_not_piOneComplete
#check @FailureOfComposition.ConcreteIndices.pointwiseIndex_comp_left
#check @FailureOfComposition.ConcreteIndices.rightCompatible_implies_piOneComplete
#check @FailureOfComposition.ConcreteIndices.rightCompatible_iff_piOneComplete
#check @FailureOfComposition.ConcreteIndices.compositionCongruence_iff_piOneComplete
#check @FailureOfComposition.ConcreteIndices.agreesWithExtensional_iff_piOneComplete
#check @FailureOfComposition.ConcreteIndices.pointwiseIndex_iff_evaluation_eq
#check @FailureOfComposition.ConcreteIndices.pi_one_characterization
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_iff_not_piOneComplete

-- Least composition congruence: witness construction, dichotomy, and quotient monoids.
#check @FailureOfComposition.CompositionClosure.IsCongruence
#check @FailureOfComposition.CompositionClosure.Generated
#check @FailureOfComposition.ConcreteIndices.GeneratedRel
#check @FailureOfComposition.CompositionClosure.base
#check @FailureOfComposition.CompositionClosure.comp
#check @FailureOfComposition.CompositionClosure.least
#check @FailureOfComposition.CompositionClosure.isCongruence
#check @FailureOfComposition.CompositionClosure.monotone
#check @FailureOfComposition.CompositionClosure.map
#check @FailureOfComposition.GeneratedCongruence.pointwise_implies_extensional_of_sigmaOneSound
#check @FailureOfComposition.GeneratedWitnessGraphs.B_comp_H
#check @FailureOfComposition.GeneratedWitnessGraphs.A_comp_H
#check @FailureOfComposition.GeneratedWitnessGraphs.AGraph_pointwise_B
#check @FailureOfComposition.GeneratedCongruence.concrete_extensional_implies_generated
#check @FailureOfComposition.GeneratedCongruence.extensional_implies_generated
#check @FailureOfComposition.GeneratedCongruence.generated_iff_extensional_of_sound
#check @FailureOfComposition.GeneratedCongruence.generated_universal_of_not_sound
#check @FailureOfComposition.GeneratedCongruence.classification
#check @FailureOfComposition.GeneratedCongruence.generated_iff_extensional_or_unsound
#check @FailureOfComposition.GeneratedCongruence.quotientMonoid
#check @FailureOfComposition.GeneratedCongruence.quotient_mul_mk
#check @FailureOfComposition.GeneratedCongruence.quotient_subsingleton_iff_not_sound
#check @FailureOfComposition.ProgramIndices.realizationIndex_composition
#check @FailureOfComposition.ProgramIndices.generatedRel_iff_graph
#check @FailureOfComposition.ProgramIndices.extensional_implies_generated
#check @FailureOfComposition.ProgramIndices.generated_iff_extensional_of_sound
#check @FailureOfComposition.ProgramIndices.generated_universal_of_not_sound
#check @FailureOfComposition.ProgramIndices.generated_congruence_classification
#check @FailureOfComposition.ProgramIndices.generated_iff_extensional_or_unsound
#check @FailureOfComposition.ProgramIndices.generated_quotient_subsingleton_iff_not_sound
#check @FailureOfComposition.ProgramIndices.generatedQuotientEquiv
#check @FailureOfComposition.ProgramIndices.generatedIndexQuotient_mul_mk
#check @FailureOfComposition.ProgramIndices.generatedIndexQuotientMonoid
#check @FailureOfComposition.ProgramIndices.generatedQuotientMulEquiv
#check @FailureOfComposition.ConcreteIndices.extensional_implies_generated
#check @FailureOfComposition.ConcreteIndices.generated_iff_extensional_of_sound
#check @FailureOfComposition.ConcreteIndices.generated_universal_of_not_sound
#check @FailureOfComposition.ConcreteIndices.generated_congruence_classification
#check @FailureOfComposition.ConcreteIndices.generated_iff_extensional_or_unsound
#check @FailureOfComposition.ConcreteIndices.pa_generated_iff_extensional
#check @FailureOfComposition.ConcreteIndices.generated_quotient_mul_mk
#check @FailureOfComposition.ConcreteIndices.generatedQuotientMulEquiv
#check @FailureOfComposition.ConcreteIndices.generated_quotient_subsingleton_iff_not_sound

-- Concrete weak totality, domain totality, and the conservativity consequence.
#check @FailureOfComposition.ConcreteIndices.WeaklyTotalIndex
#check @FailureOfComposition.ConcreteIndices.identity_comp_pointwiseIndex
#check @FailureOfComposition.ConcreteIndices.guardIndex_pointwise_identity
#check @FailureOfComposition.ConcreteIndices.guard_search_pointwise_empty
#check @FailureOfComposition.ConcreteIndices.searchIndex_not_pointwise_empty
#check @FailureOfComposition.ConcreteIndices.index_four_witnesses_of_history_divergence
#check @FailureOfComposition.ConcreteIndices.weaklyTotalIndex_identity
#check @FailureOfComposition.ConcreteIndices.not_weaklyTotalIndex_guard
#check @FailureOfComposition.ConcreteIndices.weak_totality_counterexample_of_history_divergence
#check @FailureOfComposition.ConcreteIndices.weak_totality_counterexample_via_productiveness
#check @FailureOfComposition.ConcreteIndices.weak_totality_counterexample_of_delta_one
#check @FailureOfComposition.ConcreteIndices.weak_totality_counterexample_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.weak_totality_counterexample_of_axiom_enumerator
#check @FailureOfComposition.ConcreteIndices.no_quotient_weak_totality_of_history_divergence
#check @FailureOfComposition.ConcreteIndices.no_quotient_weak_totality_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.domainGraph
#check @FailureOfComposition.ConcreteIndices.domainGraph_eval
#check @FailureOfComposition.ConcreteIndices.domainGraph_functional
#check @FailureOfComposition.ConcreteIndices.domainIndex
#check @FailureOfComposition.ConcreteIndices.domainIndex_realizes
#check @FailureOfComposition.ConcreteIndices.domainIndex_graph_equation
#check @FailureOfComposition.ConcreteIndices.RTotal
#check @FailureOfComposition.ConcreteIndices.domainGraph_pointwise_identity
#check @FailureOfComposition.ConcreteIndices.rTotal_of_pointwise_identity
#check @FailureOfComposition.ConcreteIndices.guard_rTotal_of_history_divergence
#check @FailureOfComposition.ConcreteIndices.guard_rTotal_not_weaklyTotal_of_history_divergence
#check @FailureOfComposition.ConcreteIndices.exists_rTotal_not_weaklyTotal_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.pa_exists_rTotal_not_weaklyTotal
#check @FailureOfComposition.ConcreteIndices.PiOneConservativeSentence
#check @FailureOfComposition.ConcreteIndices.insert_provable_iff_of_provable
#check @FailureOfComposition.ConcreteIndices.piOneConservativeSentence_of_provable
#check @FailureOfComposition.ConcreteIndices.convergenceAt
#check @FailureOfComposition.ConcreteIndices.convergenceAt_eval
#check @FailureOfComposition.ConcreteIndices.PointwiseConvergenceConservative
#check @FailureOfComposition.ConcreteIndices.convergenceAt_provable_of_pointwise_identity
#check @FailureOfComposition.ConcreteIndices.guard_convergenceAt_provable
#check @FailureOfComposition.ConcreteIndices.guard_pointwiseConvergenceConservative
#check @FailureOfComposition.ConcreteIndices.guard_conservative_not_weaklyTotal
#check @FailureOfComposition.ConcreteIndices.montagna_condition_two_not_one
#check @FailureOfComposition.ConcreteIndices.not_montagna_condition_two_implies_one

-- Concrete range assignment, witnesses, and the two proof routes.
#check @FailureOfComposition.ConcreteIndices.rangeOfGraph
#check @FailureOfComposition.ConcreteIndices.rangeOfGraph_eval
#check @FailureOfComposition.ConcreteIndices.rangeOfGraph_functional
#check @FailureOfComposition.ConcreteIndices.uniform_rangeOfGraph
#check @FailureOfComposition.ConcreteIndices.rangeGraph
#check @FailureOfComposition.ConcreteIndices.rangeGraph_eval
#check @FailureOfComposition.ConcreteIndices.rangeGraph_functional
#check @FailureOfComposition.ConcreteIndices.rangeIndex
#check @FailureOfComposition.ConcreteIndices.rangeIndex_realizes
#check @FailureOfComposition.ConcreteIndices.rangeIndex_graph_equation
#check @FailureOfComposition.ConcreteIndices.rangeIndex_eval
#check @FailureOfComposition.ConcreteIndices.rangeIndex_of_uniform
#check @FailureOfComposition.ConcreteIndices.rangeOfGraph_empty
#check @FailureOfComposition.ConcreteIndices.rangeIndex_empty
#check @FailureOfComposition.ConcreteIndices.rangeIndex_realization_unique
#check @FailureOfComposition.ConcreteIndices.rangeIndex_choice_independent
#check @FailureOfComposition.ConcreteIndices.probeGraph
#check @FailureOfComposition.ConcreteIndices.probeGraph_eval
#check @FailureOfComposition.ConcreteIndices.probeGraph_functional
#check @FailureOfComposition.ConcreteIndices.probeIndex
#check @FailureOfComposition.ConcreteIndices.probeIndex_realizes
#check @FailureOfComposition.ConcreteIndices.probeIndex_graph_equation
#check @FailureOfComposition.ConcreteIndices.absenceSentence
#check @FailureOfComposition.ConcreteIndices.absenceSentence_eval
#check @FailureOfComposition.ConcreteIndices.probeGraph_pointwise_empty
#check @FailureOfComposition.ConcreteIndices.probeIndex_pointwise_empty
#check @FailureOfComposition.ConcreteIndices.range_probe_at_zero
#check @FailureOfComposition.ConcreteIndices.range_probe_empty_implies_absence
#check @FailureOfComposition.ConcreteIndices.range_probeIndex_not_pointwise_empty
#check @FailureOfComposition.ConcreteIndices.range_counterexample_of_instance_refutations
#check @FailureOfComposition.ConcreteIndices.NoIndexQuotientRange
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_range_of_counterexample
#check @FailureOfComposition.ConcreteIndices.no_quotient_range_of_instance_refutations
#check @FailureOfComposition.ConcreteIndices.no_quotient_range_of_correct_assignment
#check @FailureOfComposition.ConcreteIndices.proofBotPredicate
#check @FailureOfComposition.ConcreteIndices.proofBotPredicate_numeral_refutation
#check @FailureOfComposition.ConcreteIndices.proofBotPredicate_absence_unprovable
#check @FailureOfComposition.ConcreteIndices.range_counterexample_via_godel
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_range_via_godel
#check @FailureOfComposition.ConcreteIndices.range_counterexample_of_equivalent_presentation
#check @FailureOfComposition.ConcreteIndices.range_counterexample_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_range_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.range_counterexample_of_axiom_enumerator
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_range_of_axiom_enumerator
#check @FailureOfComposition.ConcreteIndices.pa_range_counterexample
#check @FailureOfComposition.ConcreteIndices.pa_no_index_quotient_range
#check @FailureOfComposition.ConcreteIndices.historyPositive_refutable_of_divergence
#check @FailureOfComposition.ConcreteIndices.history_absence_iff_divergence
#check @FailureOfComposition.ConcreteIndices.history_absence_unprovable
#check @FailureOfComposition.ConcreteIndices.range_counterexample_of_history_divergence
#check @FailureOfComposition.ConcreteIndices.range_counterexample_via_productiveness
#check @FailureOfComposition.ConcreteIndices.range_counterexample_via_productiveness_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.range_counterexample_via_productiveness_of_axiom_enumerator
#check @FailureOfComposition.ConcreteIndices.no_index_quotient_range_via_productiveness_of_re_axioms

-- Final manuscript coverage: uniform witnesses, true-Pi-one theory, and the extensional monoid.
#check @FailureOfComposition.ConcreteIndices.UniformIndex
#check @FailureOfComposition.ConcreteIndices.uniformKleeneSentence
#check @FailureOfComposition.ConcreteIndices.uniformKleeneSentence_eval
#check @FailureOfComposition.ConcreteIndices.uniformKleeneSentence_iff_uniformSentence
#check @FailureOfComposition.ConcreteIndices.uniformIndex_iff_kleene
#check @FailureOfComposition.ConcreteIndices.identity_comp_uniformIndex
#check @FailureOfComposition.ConcreteIndices.guard_search_uniformIndex_empty
#check @FailureOfComposition.ConcreteIndices.index_four_witnesses_uniform_of_history_divergence
#check @FailureOfComposition.ConcreteIndices.obstruction_four_properties_of_re_axioms
#check @FailureOfComposition.ConcreteIndices.obstruction_four_properties_of_axiom_enumerator
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension_extends_pa
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension_standard_model
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension_consistent
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension_piOneComplete
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension_compositionCongruence
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension_agreesWithExtensional
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension_theorem_codes_not_re
#check @FailureOfComposition.PiOneCharacterization.truePiOneExtension_axiom_codes_not_re
#check @FailureOfComposition.UnaryPartrec
#check @FailureOfComposition.UnaryPartrec.mul_apply
#check @FailureOfComposition.UnaryPartrec.one_apply
#check @FailureOfComposition.UnaryPartrec.ofIndex
#check @FailureOfComposition.UnaryPartrec.ofIndex_val
#check @FailureOfComposition.UnaryPartrec.ofIndex_surjective
#check @FailureOfComposition.ConcreteIndices.generatedQuotientDenotation
#check @FailureOfComposition.ConcreteIndices.generatedQuotientDenotation_mk
#check @FailureOfComposition.ConcreteIndices.generatedQuotientDenotation_bijective
#check @FailureOfComposition.ConcreteIndices.generatedQuotientPartialRecursiveEquiv
#check @FailureOfComposition.ConcreteIndices.generatedQuotientPartialRecursiveEquiv_mk
