/-
Copyright (c) 2026 Florian Lengyel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Florian Lengyel
-/
import FailureOfComposition

/-!
Audit the axioms used by the maintained public results.
-/

#check @FailureOfComposition.complement_diagonal_productive
#check @FailureOfComposition.productive_escape_re
#check @FailureOfComposition.exists_true_unprovable_divergence
#check @FailureOfComposition.ProofSearch.numeral_negative
#check @FailureOfComposition.ProofSearch.universal_negative_bridge
#check @FailureOfComposition.ProofSearch.search_empty_implies_absence
#check @FailureOfComposition.ProofSearch.Pointwise
#check @FailureOfComposition.ProofSearch.Functional
#check @FailureOfComposition.ProofSearch.NoQuotientComposition
#check @FailureOfComposition.no_graph_quotient_composition_via_godel
#check @FailureOfComposition.no_graph_quotient_composition_via_productiveness
#check @FailureOfComposition.no_graph_quotient_composition_of_re_theorem_codes
#check @FailureOfComposition.proofBot_consistency_bridge
#check @FailureOfComposition.numeral_nonproof_of_consistency

#print axioms FailureOfComposition.no_quotient_composition
#print axioms FailureOfComposition.complement_diagonal_productive
#print axioms FailureOfComposition.productive_escape_re
#print axioms FailureOfComposition.exists_true_unprovable_divergence
#print axioms FailureOfComposition.ProofSearch.numeral_negative
#print axioms FailureOfComposition.ProofSearch.universal_negative_bridge
#print axioms FailureOfComposition.ProofSearch.search_empty_implies_absence
#print axioms FailureOfComposition.no_graph_quotient_composition_via_godel
#print axioms FailureOfComposition.no_graph_quotient_composition_via_productiveness
#print axioms FailureOfComposition.no_graph_quotient_composition_of_re_theorem_codes
#print axioms FailureOfComposition.proofBot_consistency_bridge
#print axioms FailureOfComposition.numeral_nonproof_of_consistency

#check @FailureOfComposition.Kleene.T₁_primrec
#print axioms FailureOfComposition.Kleene.T₁_primrec
#check @FailureOfComposition.Kleene.U_primrec
#print axioms FailureOfComposition.Kleene.U_primrec
#check @FailureOfComposition.Kleene.normal_form
#print axioms FailureOfComposition.Kleene.normal_form
#check @FailureOfComposition.Kleene.normal_form_equation
#print axioms FailureOfComposition.Kleene.normal_form_equation
#check @FailureOfComposition.Kleene.compIndex_primrec
#print axioms FailureOfComposition.Kleene.compIndex_primrec
#check @FailureOfComposition.Kleene.normal_form_comp
#print axioms FailureOfComposition.Kleene.normal_form_comp
#check @FailureOfComposition.Kleene.guardIndex_spec
#print axioms FailureOfComposition.Kleene.guardIndex_spec
#check @FailureOfComposition.Kleene.searchIndex_spec
#print axioms FailureOfComposition.Kleene.searchIndex_spec
#check @FailureOfComposition.Kleene.guard_after_search
#print axioms FailureOfComposition.Kleene.guard_after_search
#check @FailureOfComposition.Kleene.identity_after_search
#print axioms FailureOfComposition.Kleene.identity_after_search
#check @FailureOfComposition.Kleene.guard_eq_identity_of_divergence
#print axioms FailureOfComposition.Kleene.guard_eq_identity_of_divergence
#check @FailureOfComposition.Kleene.search_diverges_of_divergence
#print axioms FailureOfComposition.Kleene.search_diverges_of_divergence
#check @FailureOfComposition.ProgramIndices.kleeneEqAt_iff_eqAt
#print axioms FailureOfComposition.ProgramIndices.kleeneEqAt_iff_eqAt
#check @FailureOfComposition.ProgramIndices.Arithmetization.realization
#print axioms FailureOfComposition.ProgramIndices.Arithmetization.realization
#check @FailureOfComposition.ProgramIndices.Arithmetization.composition
#print axioms FailureOfComposition.ProgramIndices.Arithmetization.composition
#check @FailureOfComposition.ProgramIndices.no_index_quotient_via_godel
#print axioms FailureOfComposition.ProgramIndices.no_index_quotient_via_godel
#check @FailureOfComposition.ProgramIndices.no_index_quotient_via_productiveness
#print axioms FailureOfComposition.ProgramIndices.no_index_quotient_via_productiveness

-- Concrete evaluator milestone: print full types, not only axiom envelopes.
#check @FailureOfComposition.ConcreteWitnessGraphs.base_computation_iff
#print axioms FailureOfComposition.ConcreteWitnessGraphs.base_computation_iff
#check @CategoricalRiceShapiro.Evaluator.evalnCertificateFormula_tag_seven_iff
#print axioms CategoricalRiceShapiro.Evaluator.evalnCertificateFormula_tag_seven_iff
#check @FailureOfComposition.ConcreteEvaluator.evalnCertificateFormula_natCode_persist
#print axioms FailureOfComposition.ConcreteEvaluator.evalnCertificateFormula_natCode_persist
#check @FailureOfComposition.ConcreteEvaluator.evaluator_persistence_provable
#print axioms FailureOfComposition.ConcreteEvaluator.evaluator_persistence_provable
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_functional
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_functional
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_composition
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_composition
#check @FailureOfComposition.ConcreteWitnessGraphs.identity_computation
#print axioms FailureOfComposition.ConcreteWitnessGraphs.identity_computation
#check @FailureOfComposition.ConcreteEmptyGraph.concreteEmpty_no_computation
#print axioms FailureOfComposition.ConcreteEmptyGraph.concreteEmpty_no_computation
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_identity
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_identity
#check @FailureOfComposition.ConcreteEvaluator.eventualGraph_empty
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_empty

-- Concrete constructor laws, compiler, and history witnesses.
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_pair_code_eval
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_prec_zero_eval
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_prec_succ_eval
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_rfind_code_eval
#print axioms FailureOfComposition.ConcreteEvaluator.stageComputation_iff_evaln
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_adequate
#print axioms FailureOfComposition.ConcreteEvaluator.eventualGraph_normal_form
#print axioms FailureOfComposition.ArithmeticCodeCompiler.computes_compile
#print axioms FailureOfComposition.ArithmeticCodeCompiler.computes_unaryCompile
#print axioms FailureOfComposition.ArithmeticCodeCompiler.unaryCompile_realizes
#print axioms FailureOfComposition.HistoryWitnesses.guardCode_eval
#print axioms FailureOfComposition.HistoryWitnesses.searchCode_eval
#print axioms FailureOfComposition.HistoryWitnesses.guard_search_empty
#print axioms FailureOfComposition.HistoryWitnesses.guard_pointwise_identity
#print axioms FailureOfComposition.HistoryWitnesses.graph_noncongruence_of_history_divergence
#print axioms FailureOfComposition.theorem_codes_re_of_delta1
#print axioms FailureOfComposition.theorem_codes_re_of_axiom_codes
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_via_productiveness
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_of_delta_one
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_of_axiom_enumerator
#print axioms FailureOfComposition.theorem_codes_re_of_program_enumerator
#print axioms FailureOfComposition.ConcreteNormalForm.normalFormGraph_realizes
#print axioms FailureOfComposition.ConcreteNormalForm.computationPredicate_nat

-- Formula semidecision and unconditional realization in the concrete numbering.
#print axioms FailureOfComposition.ArithmeticFormulaAtoms.termCode_eval
#print axioms FailureOfComposition.ArithmeticFormulaAtoms.atomCode_eval
#print axioms FailureOfComposition.ArithmeticFormulaAtoms.negAtomCode_eval
#print axioms FailureOfComposition.BoundedSemidecision.computes_boundedAll
#print axioms FailureOfComposition.SigmaOneSearch.candidateSearch_domain
#print axioms FailureOfComposition.SigmaOneSearch.candidateSearch_of_functional
#print axioms FailureOfComposition.SigmaOneSearch.computes_existsProgram
#print axioms FailureOfComposition.SigmaOneSearch.computes_unionProgram
#print axioms FailureOfComposition.SigmaOneRealization.semidecision_exists
#print axioms FailureOfComposition.SigmaOneRealization.realize_of_semidecides
#print axioms FailureOfComposition.SigmaOneRealization.realize_graph
#print axioms FailureOfComposition.ConcreteEvaluator.arithmetization

-- Both the chosen-presentation and r.e.-axiom forms of the Godel-II proof.
#print axioms FailureOfComposition.ConcreteIndices.index_noncongruence_via_godel
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_via_godel
#print axioms FailureOfComposition.ConcreteIndices.pa_no_index_quotient_via_godel
#print axioms FailureOfComposition.ConcreteIndices.index_noncongruence_via_godel_of_equivalent_presentation
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_via_godel_of_equivalent_presentation
#print axioms FailureOfComposition.CraigPresentation.exists_craig_presentation
#print axioms FailureOfComposition.ConcreteIndices.index_noncongruence_via_godel_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_via_godel_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_via_godel_of_axiom_enumerator

-- Quotient-set transport and representative-level composition preservation.
#print axioms FailureOfComposition.ArithmetizationTransport.translate_uniform
#print axioms FailureOfComposition.ArithmetizationTransport.translate_pointwise_iff
#print axioms FailureOfComposition.ArithmetizationTransport.translate_roundtrip
#print axioms FailureOfComposition.ArithmetizationTransport.translate_composition
#print axioms FailureOfComposition.ArithmetizationTransport.quotientEquiv
#print axioms FailureOfComposition.ArithmetizationTransport.quotientEquiv_composition
#print axioms FailureOfComposition.ConcreteTransport.toConcrete_uniform
#print axioms FailureOfComposition.ConcreteTransport.toConcrete_pointwise_iff
#print axioms FailureOfComposition.ConcreteTransport.quotientEquiv
#print axioms FailureOfComposition.ConcreteTransport.toConcrete_composition

-- Pi-one completeness, with effectiveness absent and consistency explicit.
#print axioms FailureOfComposition.quotient_composition_exists_iff
#print axioms FailureOfComposition.PiOneCharacterization.pointwise_comp_left
#print axioms FailureOfComposition.PiOneCharacterization.congruence_iff_rightCompatible
#print axioms FailureOfComposition.PiOneCharacterization.graph_noncongruence_of_true_unprovable_pi_one
#print axioms FailureOfComposition.PiOneCharacterization.rightCompatible_implies_piOneComplete
#print axioms FailureOfComposition.PiOneCharacterization.sigma_one_sound_of_pi_one_complete
#print axioms FailureOfComposition.PiOneCharacterization.pointwise_iff_extensional
#print axioms FailureOfComposition.PiOneCharacterization.rightCompatible_iff_piOneComplete
#print axioms FailureOfComposition.PiOneCharacterization.compositionCongruence_iff_piOneComplete
#print axioms FailureOfComposition.PiOneCharacterization.agreesWithExtensional_iff_piOneComplete
#print axioms FailureOfComposition.PiOneCharacterization.characterization
#print axioms FailureOfComposition.PiOneCharacterization.quotient_composition_exists_iff_congruence
#print axioms FailureOfComposition.PiOneCharacterization.no_quotient_composition_iff_not_piOneComplete
#print axioms FailureOfComposition.ProgramIndices.rightCompatible_iff_graph
#print axioms FailureOfComposition.ProgramIndices.compositionCongruence_iff_graph
#print axioms FailureOfComposition.ProgramIndices.agreesWithExtensional_iff_graph
#print axioms FailureOfComposition.ProgramIndices.rightCompatible_iff_piOneComplete
#print axioms FailureOfComposition.ProgramIndices.compositionCongruence_iff_piOneComplete
#print axioms FailureOfComposition.ProgramIndices.agreesWithExtensional_iff_piOneComplete
#print axioms FailureOfComposition.ProgramIndices.pointwiseIndex_iff_evaluation_eq
#print axioms FailureOfComposition.ProgramIndices.characterization
#print axioms FailureOfComposition.ProgramIndices.quotient_composition_exists_iff_congruence
#print axioms FailureOfComposition.ProgramIndices.no_index_quotient_iff_not_piOneComplete
#print axioms FailureOfComposition.ConcreteIndices.pointwiseIndex_comp_left
#print axioms FailureOfComposition.ConcreteIndices.rightCompatible_implies_piOneComplete
#print axioms FailureOfComposition.ConcreteIndices.rightCompatible_iff_piOneComplete
#print axioms FailureOfComposition.ConcreteIndices.compositionCongruence_iff_piOneComplete
#print axioms FailureOfComposition.ConcreteIndices.agreesWithExtensional_iff_piOneComplete
#print axioms FailureOfComposition.ConcreteIndices.pointwiseIndex_iff_evaluation_eq
#print axioms FailureOfComposition.ConcreteIndices.pi_one_characterization
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_iff_not_piOneComplete

-- Least composition congruence: witness construction, dichotomy, and quotient monoids.
#print axioms FailureOfComposition.CompositionClosure.base
#print axioms FailureOfComposition.CompositionClosure.comp
#print axioms FailureOfComposition.CompositionClosure.least
#print axioms FailureOfComposition.CompositionClosure.isCongruence
#print axioms FailureOfComposition.CompositionClosure.monotone
#print axioms FailureOfComposition.CompositionClosure.map
#print axioms FailureOfComposition.GeneratedCongruence.pointwise_implies_extensional_of_sigmaOneSound
#print axioms FailureOfComposition.GeneratedWitnessGraphs.B_comp_H
#print axioms FailureOfComposition.GeneratedWitnessGraphs.A_comp_H
#print axioms FailureOfComposition.GeneratedWitnessGraphs.AGraph_pointwise_B
#print axioms FailureOfComposition.GeneratedCongruence.concrete_extensional_implies_generated
#print axioms FailureOfComposition.GeneratedCongruence.extensional_implies_generated
#print axioms FailureOfComposition.GeneratedCongruence.generated_iff_extensional_of_sound
#print axioms FailureOfComposition.GeneratedCongruence.generated_universal_of_not_sound
#print axioms FailureOfComposition.GeneratedCongruence.classification
#print axioms FailureOfComposition.GeneratedCongruence.generated_iff_extensional_or_unsound
#print axioms FailureOfComposition.GeneratedCongruence.quotientMonoid
#print axioms FailureOfComposition.GeneratedCongruence.quotient_mul_mk
#print axioms FailureOfComposition.GeneratedCongruence.quotient_subsingleton_iff_not_sound
#print axioms FailureOfComposition.ProgramIndices.realizationIndex_composition
#print axioms FailureOfComposition.ProgramIndices.generatedRel_iff_graph
#print axioms FailureOfComposition.ProgramIndices.extensional_implies_generated
#print axioms FailureOfComposition.ProgramIndices.generated_iff_extensional_of_sound
#print axioms FailureOfComposition.ProgramIndices.generated_universal_of_not_sound
#print axioms FailureOfComposition.ProgramIndices.generated_congruence_classification
#print axioms FailureOfComposition.ProgramIndices.generated_iff_extensional_or_unsound
#print axioms FailureOfComposition.ProgramIndices.generated_quotient_subsingleton_iff_not_sound
#print axioms FailureOfComposition.ProgramIndices.generatedQuotientEquiv
#print axioms FailureOfComposition.ProgramIndices.generatedIndexQuotient_mul_mk
#print axioms FailureOfComposition.ProgramIndices.generatedIndexQuotientMonoid
#print axioms FailureOfComposition.ProgramIndices.generatedQuotientMulEquiv
#print axioms FailureOfComposition.ConcreteIndices.extensional_implies_generated
#print axioms FailureOfComposition.ConcreteIndices.generated_iff_extensional_of_sound
#print axioms FailureOfComposition.ConcreteIndices.generated_universal_of_not_sound
#print axioms FailureOfComposition.ConcreteIndices.generated_congruence_classification
#print axioms FailureOfComposition.ConcreteIndices.generated_iff_extensional_or_unsound
#print axioms FailureOfComposition.ConcreteIndices.pa_generated_iff_extensional
#print axioms FailureOfComposition.ConcreteIndices.generated_quotient_mul_mk
#print axioms FailureOfComposition.ConcreteIndices.generatedQuotientMulEquiv
#print axioms FailureOfComposition.ConcreteIndices.generated_quotient_subsingleton_iff_not_sound

-- Concrete weak totality, domain totality, and the conservativity consequence.
#print axioms FailureOfComposition.ConcreteIndices.WeaklyTotalIndex
#print axioms FailureOfComposition.ConcreteIndices.identity_comp_pointwiseIndex
#print axioms FailureOfComposition.ConcreteIndices.guardIndex_pointwise_identity
#print axioms FailureOfComposition.ConcreteIndices.guard_search_pointwise_empty
#print axioms FailureOfComposition.ConcreteIndices.searchIndex_not_pointwise_empty
#print axioms FailureOfComposition.ConcreteIndices.index_four_witnesses_of_history_divergence
#print axioms FailureOfComposition.ConcreteIndices.weaklyTotalIndex_identity
#print axioms FailureOfComposition.ConcreteIndices.not_weaklyTotalIndex_guard
#print axioms FailureOfComposition.ConcreteIndices.weak_totality_counterexample_of_history_divergence
#print axioms FailureOfComposition.ConcreteIndices.weak_totality_counterexample_via_productiveness
#print axioms FailureOfComposition.ConcreteIndices.weak_totality_counterexample_of_delta_one
#print axioms FailureOfComposition.ConcreteIndices.weak_totality_counterexample_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.weak_totality_counterexample_of_axiom_enumerator
#print axioms FailureOfComposition.ConcreteIndices.no_quotient_weak_totality_of_history_divergence
#print axioms FailureOfComposition.ConcreteIndices.no_quotient_weak_totality_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.domainGraph
#print axioms FailureOfComposition.ConcreteIndices.domainGraph_eval
#print axioms FailureOfComposition.ConcreteIndices.domainGraph_functional
#print axioms FailureOfComposition.ConcreteIndices.domainIndex
#print axioms FailureOfComposition.ConcreteIndices.domainIndex_realizes
#print axioms FailureOfComposition.ConcreteIndices.domainIndex_graph_equation
#print axioms FailureOfComposition.ConcreteIndices.RTotal
#print axioms FailureOfComposition.ConcreteIndices.domainGraph_pointwise_identity
#print axioms FailureOfComposition.ConcreteIndices.rTotal_of_pointwise_identity
#print axioms FailureOfComposition.ConcreteIndices.guard_rTotal_of_history_divergence
#print axioms FailureOfComposition.ConcreteIndices.guard_rTotal_not_weaklyTotal_of_history_divergence
#print axioms FailureOfComposition.ConcreteIndices.exists_rTotal_not_weaklyTotal_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.pa_exists_rTotal_not_weaklyTotal
#print axioms FailureOfComposition.ConcreteIndices.PiOneConservativeSentence
#print axioms FailureOfComposition.ConcreteIndices.insert_provable_iff_of_provable
#print axioms FailureOfComposition.ConcreteIndices.piOneConservativeSentence_of_provable
#print axioms FailureOfComposition.ConcreteIndices.convergenceAt
#print axioms FailureOfComposition.ConcreteIndices.convergenceAt_eval
#print axioms FailureOfComposition.ConcreteIndices.PointwiseConvergenceConservative
#print axioms FailureOfComposition.ConcreteIndices.convergenceAt_provable_of_pointwise_identity
#print axioms FailureOfComposition.ConcreteIndices.guard_convergenceAt_provable
#print axioms FailureOfComposition.ConcreteIndices.guard_pointwiseConvergenceConservative
#print axioms FailureOfComposition.ConcreteIndices.guard_conservative_not_weaklyTotal
#print axioms FailureOfComposition.ConcreteIndices.montagna_condition_two_not_one
#print axioms FailureOfComposition.ConcreteIndices.not_montagna_condition_two_implies_one

-- Concrete range assignment, witnesses, and the two proof routes.
#print axioms FailureOfComposition.ConcreteIndices.rangeOfGraph
#print axioms FailureOfComposition.ConcreteIndices.rangeOfGraph_eval
#print axioms FailureOfComposition.ConcreteIndices.rangeOfGraph_functional
#print axioms FailureOfComposition.ConcreteIndices.uniform_rangeOfGraph
#print axioms FailureOfComposition.ConcreteIndices.rangeGraph
#print axioms FailureOfComposition.ConcreteIndices.rangeGraph_eval
#print axioms FailureOfComposition.ConcreteIndices.rangeGraph_functional
#print axioms FailureOfComposition.ConcreteIndices.rangeIndex
#print axioms FailureOfComposition.ConcreteIndices.rangeIndex_realizes
#print axioms FailureOfComposition.ConcreteIndices.rangeIndex_graph_equation
#print axioms FailureOfComposition.ConcreteIndices.rangeIndex_eval
#print axioms FailureOfComposition.ConcreteIndices.rangeIndex_of_uniform
#print axioms FailureOfComposition.ConcreteIndices.rangeOfGraph_empty
#print axioms FailureOfComposition.ConcreteIndices.rangeIndex_empty
#print axioms FailureOfComposition.ConcreteIndices.rangeIndex_realization_unique
#print axioms FailureOfComposition.ConcreteIndices.rangeIndex_choice_independent
#print axioms FailureOfComposition.ConcreteIndices.probeGraph
#print axioms FailureOfComposition.ConcreteIndices.probeGraph_eval
#print axioms FailureOfComposition.ConcreteIndices.probeGraph_functional
#print axioms FailureOfComposition.ConcreteIndices.probeIndex
#print axioms FailureOfComposition.ConcreteIndices.probeIndex_realizes
#print axioms FailureOfComposition.ConcreteIndices.probeIndex_graph_equation
#print axioms FailureOfComposition.ConcreteIndices.absenceSentence
#print axioms FailureOfComposition.ConcreteIndices.absenceSentence_eval
#print axioms FailureOfComposition.ConcreteIndices.probeGraph_pointwise_empty
#print axioms FailureOfComposition.ConcreteIndices.probeIndex_pointwise_empty
#print axioms FailureOfComposition.ConcreteIndices.range_probe_at_zero
#print axioms FailureOfComposition.ConcreteIndices.range_probe_empty_implies_absence
#print axioms FailureOfComposition.ConcreteIndices.range_probeIndex_not_pointwise_empty
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_of_instance_refutations
#print axioms FailureOfComposition.ConcreteIndices.NoIndexQuotientRange
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_range_of_counterexample
#print axioms FailureOfComposition.ConcreteIndices.no_quotient_range_of_instance_refutations
#print axioms FailureOfComposition.ConcreteIndices.no_quotient_range_of_correct_assignment
#print axioms FailureOfComposition.ConcreteIndices.proofBotPredicate
#print axioms FailureOfComposition.ConcreteIndices.proofBotPredicate_numeral_refutation
#print axioms FailureOfComposition.ConcreteIndices.proofBotPredicate_absence_unprovable
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_via_godel
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_range_via_godel
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_of_equivalent_presentation
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_range_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_of_axiom_enumerator
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_range_of_axiom_enumerator
#print axioms FailureOfComposition.ConcreteIndices.pa_range_counterexample
#print axioms FailureOfComposition.ConcreteIndices.pa_no_index_quotient_range
#print axioms FailureOfComposition.ConcreteIndices.historyPositive_refutable_of_divergence
#print axioms FailureOfComposition.ConcreteIndices.history_absence_iff_divergence
#print axioms FailureOfComposition.ConcreteIndices.history_absence_unprovable
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_of_history_divergence
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_via_productiveness
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_via_productiveness_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.range_counterexample_via_productiveness_of_axiom_enumerator
#print axioms FailureOfComposition.ConcreteIndices.no_index_quotient_range_via_productiveness_of_re_axioms

-- Final manuscript coverage: uniform witnesses, true-Pi-one theory, and the extensional monoid.
#print axioms FailureOfComposition.ConcreteIndices.UniformIndex
#print axioms FailureOfComposition.ConcreteIndices.uniformKleeneSentence
#print axioms FailureOfComposition.ConcreteIndices.uniformKleeneSentence_eval
#print axioms FailureOfComposition.ConcreteIndices.uniformKleeneSentence_iff_uniformSentence
#print axioms FailureOfComposition.ConcreteIndices.uniformIndex_iff_kleene
#print axioms FailureOfComposition.ConcreteIndices.identity_comp_uniformIndex
#print axioms FailureOfComposition.ConcreteIndices.guard_search_uniformIndex_empty
#print axioms FailureOfComposition.ConcreteIndices.index_four_witnesses_uniform_of_history_divergence
#print axioms FailureOfComposition.ConcreteIndices.obstruction_four_properties_of_re_axioms
#print axioms FailureOfComposition.ConcreteIndices.obstruction_four_properties_of_axiom_enumerator
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension_extends_pa
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension_standard_model
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension_consistent
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension_piOneComplete
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension_compositionCongruence
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension_agreesWithExtensional
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension_theorem_codes_not_re
#print axioms FailureOfComposition.PiOneCharacterization.truePiOneExtension_axiom_codes_not_re
#print axioms FailureOfComposition.UnaryPartrec
#print axioms FailureOfComposition.UnaryPartrec.mul_apply
#print axioms FailureOfComposition.UnaryPartrec.one_apply
#print axioms FailureOfComposition.UnaryPartrec.ofIndex
#print axioms FailureOfComposition.UnaryPartrec.ofIndex_val
#print axioms FailureOfComposition.UnaryPartrec.ofIndex_surjective
#print axioms FailureOfComposition.ConcreteIndices.generatedQuotientDenotation
#print axioms FailureOfComposition.ConcreteIndices.generatedQuotientDenotation_mk
#print axioms FailureOfComposition.ConcreteIndices.generatedQuotientDenotation_bijective
#print axioms FailureOfComposition.ConcreteIndices.generatedQuotientPartialRecursiveEquiv
#print axioms FailureOfComposition.ConcreteIndices.generatedQuotientPartialRecursiveEquiv_mk
