/-
Copyright (c) 2026 Florian Lengyel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Florian Lengyel
-/
import FailureOfComposition.GeneratedGraphDefinitions
import FailureOfComposition.GeneratedWitnessPointwise
import FailureOfComposition.SigmaOneRealization

/-!
Extensional containment in the generated composition congruence.
-/

set_option autoImplicit false

open LO LO.FirstOrder LO.FirstOrder.Arithmetic LO.Entailment

namespace FailureOfComposition.GeneratedCongruence
open ProofSearch PiOneCharacterization GeneratedWitnessGraphs

def concreteGraph (e : ℕ) : FunctionalGraph :=
  ⟨ConcreteEvaluator.eventualGraph e, ConcreteEvaluator.eventualGraph_functional e⟩

def intersectionGraph (F G : FunctionalGraph) : FunctionalGraph :=
  ⟨intersection F.val G.val, intersection_functional F.val G.val F.property⟩

/-- PA-uniform equality in particular identifies standard graph extensions. -/
theorem uniform_extensional {F G : Graph} (h : Uniform 𝗣𝗔 F G) : Extensional F G := by
  have hs : ℕ↓[ℒₒᵣ] ⊧ uniformSentence F G :=
    consequence_iff.mp (Theory.Proof.sound h) ℕ inferInstance
  simpa only [Extensional, models_iff, uniformSentence_eval] using hs

/-- The least-stage witnesses identify a concrete graph with its intersection
with any extensionally equal graph in every generated congruence. -/
theorem concrete_rel_intersection (T : ArithmeticTheory) [𝗣𝗔 ⪯ T]
    (e : ℕ) (G : FunctionalGraph) (hExt : Extensional (concreteGraph e).val G.val) :
    Rel T (concreteGraph e) (intersectionGraph (concreteGraph e) G) := by
  let A : FunctionalGraph := ⟨AGraph e G.val, AGraph_functional e G.val⟩
  let B : FunctionalGraph := ⟨BGraph e, BGraph_functional e⟩
  let H : FunctionalGraph := ⟨HGraph e, HGraph_functional e⟩
  have hAB : Rel T A B := rel_base T
    (fun n => WeakerThan.pbl (AGraph_pointwise_B e G.val hExt n))
  have hComp : Rel T (functionalComp A H) (functionalComp B H) :=
    rel_comp T hAB (rel_refl T H)
  have hB : Rel T (functionalComp B H) (concreteGraph e) :=
    rel_of_uniform T (B_comp_H e)
  have hA : Rel T (functionalComp A H) (intersectionGraph (concreteGraph e) G) :=
    rel_of_uniform T (A_comp_H e G.val)
  exact rel_trans T (rel_symm T hB) (rel_trans T (rel_symm T hComp) hA)

theorem concrete_extensional_implies_generated (T : ArithmeticTheory) [𝗣𝗔 ⪯ T]
    (e d : ℕ) (h : Extensional (concreteGraph e).val (concreteGraph d).val) :
    Rel T (concreteGraph e) (concreteGraph d) := by
  have he := concrete_rel_intersection T e (concreteGraph d) h
  have hd := concrete_rel_intersection T d (concreteGraph e) (fun x y => (h x y).symm)
  have hc : Rel T (intersectionGraph (concreteGraph e) (concreteGraph d))
      (intersectionGraph (concreteGraph d) (concreteGraph e)) :=
    rel_of_uniform T (intersection_comm_uniform _ _)
  exact rel_trans T he (rel_trans T hc (rel_symm T hd))

/-- Extensional equality is contained in the congruence generated by pointwise
provability for every extension of PA, without consistency or soundness. -/
theorem extensional_implies_generated (T : ArithmeticTheory) [𝗣𝗔 ⪯ T]
    (F G : FunctionalGraph) (h : Extensional F.val G.val) : Rel T F G := by
  obtain ⟨e, he⟩ := SigmaOneRealization.realize_graph F.val F.property
  obtain ⟨d, hd⟩ := SigmaOneRealization.realize_graph G.val G.property
  have hext := uniform_extensional he
  have hdxt := uniform_extensional hd
  have hed : Extensional (concreteGraph e).val (concreteGraph d).val :=
    fun x y => (hext x y).trans ((h x y).trans (hdxt x y).symm)
  have heR : Rel T (concreteGraph e) F := rel_of_uniform T he
  have hdR : Rel T (concreteGraph d) G := rel_of_uniform T hd
  exact rel_trans T (rel_symm T heR)
    (rel_trans T (concrete_extensional_implies_generated T e d hed) hdR)

end FailureOfComposition.GeneratedCongruence
