/-
Copyright (c) 2026 Florian Lengyel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Florian Lengyel
-/
import FailureOfComposition.QuotientObstruction
import FailureOfComposition.Productiveness
import FailureOfComposition.ProductiveDivergence
import FailureOfComposition.TheoryEnumerability
import FailureOfComposition.ProofSearchTemplate
import FailureOfComposition.GraphQuotient
import FailureOfComposition.GodelGraph
import FailureOfComposition.ProductiveGraph
import FailureOfComposition.KleeneNormalForm
import FailureOfComposition.AxiomEnumeration
import FailureOfComposition.ComputationSearchIndices
import FailureOfComposition.ProgramIndices
import FailureOfComposition.ConcreteWitnessGraphs
import FailureOfComposition.MinimizationPersistence
import FailureOfComposition.ConcreteEmptyGraph
import FailureOfComposition.ConcretePersistence
import FailureOfComposition.ConcreteEvaluatorGraph
import FailureOfComposition.ConcreteConstructorGraphs
import FailureOfComposition.ConcreteRecursionGraph
import FailureOfComposition.ConcreteMinimizationGraph
import FailureOfComposition.ConcreteAdequacy
import FailureOfComposition.ConcreteNormalForm
import FailureOfComposition.ConcreteDiagonal
import FailureOfComposition.ProgramGraph
import FailureOfComposition.ArithmeticProgramOperations
import FailureOfComposition.ArithmeticCodeCompiler
import FailureOfComposition.HistoryWitnesses
import FailureOfComposition.HistoryObstruction
import FailureOfComposition.ConcreteIndexObstruction
import FailureOfComposition.ArithmeticFormulaAtoms
import FailureOfComposition.BoundedSemidecision
import FailureOfComposition.SigmaOneSemidecisionCore
import FailureOfComposition.SigmaOneSearch
import FailureOfComposition.SigmaOneGraphWitness
import FailureOfComposition.SigmaOneRealization
import FailureOfComposition.ConcreteGodel
import FailureOfComposition.ArithmetizationTransport
import FailureOfComposition.ConcreteTransport
import FailureOfComposition.CraigPresentation
import FailureOfComposition.ConcreteGodelRE
import FailureOfComposition.QuotientComposition
import FailureOfComposition.PiOneDefinitions
import FailureOfComposition.PiOneCongruence
import FailureOfComposition.PiOneExtensionality
import FailureOfComposition.PiOneNecessity
import FailureOfComposition.PiOneCharacterization
import FailureOfComposition.PiOneIndexCharacterization
import FailureOfComposition.ConcretePiOneCharacterization
import FailureOfComposition.CompositionClosure
import FailureOfComposition.GeneratedGraphDefinitions
import FailureOfComposition.GeneratedSoundness
import FailureOfComposition.GeneratedWitnessGraphs
import FailureOfComposition.GeneratedWitnessPointwise
import FailureOfComposition.GeneratedExtensionality
import FailureOfComposition.GeneratedCollapse
import FailureOfComposition.GeneratedQuotient
import FailureOfComposition.GeneratedClassification
import FailureOfComposition.GeneratedIndexTransport
import FailureOfComposition.GeneratedIndexClassification
import FailureOfComposition.GeneratedIndexQuotient
import FailureOfComposition.ConcreteGeneratedCongruence
import FailureOfComposition.ConcreteWeakTotality
import FailureOfComposition.DomainTotality
import FailureOfComposition.ConservativityConsequence
import FailureOfComposition.RangeAssignment
import FailureOfComposition.RangeWitness
import FailureOfComposition.RangeGodel
import FailureOfComposition.RangeProductive
import FailureOfComposition.ManuscriptObstruction
import FailureOfComposition.TruePiOneTheory
import FailureOfComposition.PartialRecursiveQuotient

/-!
The maintained formalization of the failure-of-composition manuscript.
-/
