name = "CategoricalRiceShapiro"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["FailureOfComposition"]
[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "065356127b1dc0016f66b7283ce0ce2c4055aa55"

[[require]]
name = "Foundation"
git = "https://github.com/FormalizedFormalLogic/Foundation.git"
rev = "e72cfe981aa65166f37fa4e2584f4806bc48d72f"

[[lean_lib]]
name = "CategoricalRiceShapiro"

[[lean_lib]]
name = "FailureOfComposition"
