name = "CategoricalRiceShapiro"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["FailureOfComposition"]
[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[require]]
name = "Foundation"
git = "https://github.com/FormalizedFormalLogic/Foundation.git"
rev = "a3dd617f88bda178eb6c206dd5db91f88b6a2a42"

[[lean_lib]]
name = "CategoricalRiceShapiro"

[[lean_lib]]
name = "FailureOfComposition"
