/-
Copyright (c) 2026 Florian Lengyel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Florian Lengyel
-/
import FailureOfComposition.Palomar.GeneratedCongruenceInterface

/-!
# Independent generated quotient and partial-recursive target

These definitions expose the quotient and actual-function target used by the
ninth eligible statement.  The generated relation and concrete composition
operation are the independent definitions already used by the classification.
-/

set_option autoImplicit false

namespace FailureOfComposition.Palomar.Arithmetic.Evaluator

/-- Program indices modulo the least composition congruence generated by
external pointwise provability. -/
abbrev GeneratedQuotient (T : Theory) :=
  Quot (GeneratedRel T)

/-- The generated-quotient class represented by a natural-number index. -/
def generatedQuotientMk (T : Theory) (e : ℕ) : GeneratedQuotient T :=
  Quot.mk _ e

/-- Multiplication is induced by the fixed concrete composition index. -/
instance generatedQuotientMul (T : Theory) : Mul (GeneratedQuotient T) where
  mul := Quot.lift₂ (fun e d ↦ generatedQuotientMk T (compIndex e d))
    (by
      intro a b b' hb
      exact Quot.sound (fun R hR hbase ↦
        hR.2 a a b b' (hR.1.refl a) (hb R hR hbase)))
    (by
      intro a a' b ha
      exact Quot.sound (fun R hR hbase ↦
        hR.2 a a' b b (ha R hR hbase) (hR.1.refl b)))

/-- The fixed identity-program class is the independent quotient unit. -/
instance generatedQuotientOne (T : Theory) : One (GeneratedQuotient T) where
  one := generatedQuotientMk T identityIndex

/-- Unary partial recursive functions, identified as actual partial maps. -/
def UnaryPartrec := { f : ℕ → Part ℕ // Nat.Partrec f }

namespace UnaryPartrec

/-- Multiplication applies the right partial map before the left one. -/
instance : Mul UnaryPartrec where
  mul f g :=
    ⟨fun x ↦ (g.val x).bind f.val, Nat.Partrec.comp f.property g.property⟩

/-- The unit is the total partial identity. -/
instance : One UnaryPartrec where
  one := ⟨Part.some, Nat.Partrec.Code.exists_code.mpr
    ⟨Nat.Partrec.Code.id, funext Nat.Partrec.Code.eval_id⟩⟩

/-- The actual partial function denoted by an index. -/
def ofIndex (e : ℕ) : UnaryPartrec :=
  ⟨actualEval e, Nat.Partrec.Code.exists_code.mpr
    ⟨Denumerable.ofNat Nat.Partrec.Code e, rfl⟩⟩

end UnaryPartrec

end FailureOfComposition.Palomar.Arithmetic.Evaluator
