/-
Copyright (c) 2026 Florian Lengyel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Florian Lengyel
-/
import FailureOfComposition.Palomar.GodelQuotientBridge
import FailureOfComposition.Palomar.PiOneBridge
import FailureOfComposition.Palomar.GeneratedCongruenceBridge
import FailureOfComposition.Palomar.WeakTotalityBridge

/-! Proved cumulative counterpart of the six-result Challenge checkpoint. -/

set_option autoImplicit false

namespace FailureOfComposition.Palomar

open Arithmetic Arithmetic.Evaluator

/-- Theorem 1: four productive witnesses with two internal uniform clauses. -/
theorem obstruction_four_properties
    (T : Arithmetic.Theory)
    (hPA : Arithmetic.DeductivelyExtends Arithmetic.Peano T)
    (hCons : Arithmetic.Consistent T)
    (hT : REPred (Arithmetic.AxiomCodes T)) :
    ∃ f g : ℕ,
      Arithmetic.Evaluator.PointwiseIndex T f Arithmetic.Evaluator.identityIndex ∧
      Arithmetic.Evaluator.UniformIndex T (Arithmetic.Evaluator.compIndex f g)
        Arithmetic.Evaluator.emptyIndex ∧
      Arithmetic.Evaluator.UniformIndex T
        (Arithmetic.Evaluator.compIndex Arithmetic.Evaluator.identityIndex g) g ∧
      ¬Arithmetic.Evaluator.PointwiseIndex T g Arithmetic.Evaluator.emptyIndex := by
  exact Arithmetic.Evaluator.obstruction_four_properties T hPA hCons hT

/-- Corollary 2, productive route: no operation on the pointwise-provability
quotient can obey the representative composition equation. -/
theorem no_quotient_composition_productive
    (T : Arithmetic.Theory)
    (hPA : Arithmetic.DeductivelyExtends Arithmetic.Peano T)
    (hCons : Arithmetic.Consistent T)
    (hT : REPred (Arithmetic.AxiomCodes T)) :
    ¬∃ C : Arithmetic.Evaluator.IndexQuotient T →
        Arithmetic.Evaluator.IndexQuotient T →
        Arithmetic.Evaluator.IndexQuotient T,
      ∀ e d : ℕ,
        C (Arithmetic.Evaluator.indexQuotientMk T e)
            (Arithmetic.Evaluator.indexQuotientMk T d) =
          Arithmetic.Evaluator.indexQuotientMk T
            (Arithmetic.Evaluator.compIndex e d) := by
  exact Arithmetic.Evaluator.no_quotient_composition_of_four_properties T hPA
    (obstruction_four_properties T hPA hCons hT)

/-- Corollary 3 with the identical statement and assumptions, by the separate
maintained Gödel-II and Craig-presentation route. -/
theorem no_quotient_composition_godel
    (T : Arithmetic.Theory)
    (hPA : Arithmetic.DeductivelyExtends Arithmetic.Peano T)
    (hCons : Arithmetic.Consistent T)
    (hT : REPred (Arithmetic.AxiomCodes T)) :
    ¬∃ C : Arithmetic.Evaluator.IndexQuotient T →
        Arithmetic.Evaluator.IndexQuotient T →
        Arithmetic.Evaluator.IndexQuotient T,
      ∀ e d : ℕ,
        C (Arithmetic.Evaluator.indexQuotientMk T e)
            (Arithmetic.Evaluator.indexQuotientMk T d) =
          Arithmetic.Evaluator.indexQuotientMk T
            (Arithmetic.Evaluator.compIndex e d) := by
  exact Arithmetic.Evaluator.no_quotient_composition_godel T hPA hCons hT

/-- Theorem 4: right compatibility, composition congruence, true-Π₁
completeness, and agreement with actual partial-function equality coincide. -/
theorem pi_one_characterization
    (T : Arithmetic.Theory)
    (hPA : Arithmetic.DeductivelyExtends Arithmetic.Peano T)
    (hCons : Arithmetic.Consistent T) :
    (Arithmetic.Evaluator.RightCompatible T ↔
      Arithmetic.Evaluator.CompositionCongruence T) ∧
    (Arithmetic.Evaluator.CompositionCongruence T ↔
      Arithmetic.PiOneComplete T) ∧
    (Arithmetic.PiOneComplete T ↔
      Arithmetic.Evaluator.AgreesWithExtensional T) := by
  exact Arithmetic.Evaluator.pi_one_characterization T hPA hCons

/-- Theorem 5: the least two-sided composition congruence generated by
pointwise provability is extensional under Σ₁ soundness and universal when
Σ₁ soundness fails. -/
theorem generated_congruence_classification
    (T : Arithmetic.Theory)
    (hPA : Arithmetic.DeductivelyExtends Arithmetic.Peano T) :
    (Arithmetic.SigmaOneSound T →
      ∀ e d : ℕ, Arithmetic.Evaluator.GeneratedRel T e d ↔
        Arithmetic.Evaluator.actualEval e = Arithmetic.Evaluator.actualEval d) ∧
    (¬Arithmetic.SigmaOneSound T →
      ∀ e d : ℕ, Arithmetic.Evaluator.GeneratedRel T e d) := by
  exact Arithmetic.Evaluator.generated_congruence_classification T hPA

/-- Proposition 5: the exact compiled guard is pointwise equal to identity but
is not weakly total, while identity is weakly total. -/
theorem weak_totality_counterexample
    (T : Arithmetic.Theory)
    (hPA : Arithmetic.DeductivelyExtends Arithmetic.Peano T)
    (hCons : Arithmetic.Consistent T)
    (hT : REPred (Arithmetic.AxiomCodes T)) :
    ∃ d : ℕ, Arithmetic.Evaluator.PointwiseIndex T
        (Arithmetic.Evaluator.guardIndex d) Arithmetic.Evaluator.identityIndex ∧
      ¬Arithmetic.Evaluator.WeaklyTotalIndex T (Arithmetic.Evaluator.guardIndex d) ∧
      Arithmetic.Evaluator.WeaklyTotalIndex T Arithmetic.Evaluator.identityIndex := by
  exact Arithmetic.Evaluator.weak_totality_counterexample T hPA hCons hT

end FailureOfComposition.Palomar
